[theme]
#Primary accent color for interactive elements
primaryColor = '#7792E3'

#Background color
backgroundColor = '#494949'

#Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#435346'

#Main text color
textColor = '#FFFFFF'

#Font family for all text in the app, except code blocks
#Accepted values (serif | sans serif | monospace)
#Default: "sans serif"
font = "sans serif" 